services: 
  aichords:
    image: aichords
    container_name: aichords_app
    restart: always
    build: .
    ports:
    - 8000:8000
    volumes:
    - ./auth/:/etc/auth/:ro
    networks:
    - aichords

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    build: 
      context: ./config/nginx
      args:
      - ENV=${ENV}
    volumes:
    - ./auth/:/etc/auth/:ro
    - ./certbot/www/:/var/www/certbot:ro
    - ./certbot/conf/:/etc/nginx/ssl/:ro
    - ./config/chords/:/var/www/chords:ro
    ports:
#    - 80:80
    - 443:443
    environment:
      ENV: ${ENV}
    networks:
    - aichords
    extra_hosts:
    - "host.docker.internal:host-gateway"
     
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
      MONGO_INITDB_DATABASE: aichords
    secrets:
    - mongo_root
    - mongo_root_password
    ports:
    - 27017:27017
    networks:
    - aichords
    volumes:
    - ./mongo/data/:/data/db
    - ./auth/:/data/auth
    - ./config/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME_FILE: /run/secrets/mongo_root
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongo_root_password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: false
      #ME_CONFIG_MONGODB_URL: "mongodb://admin:pass@mongo:27017/"
      #ME_CONFIG_BASICAUTH_USERNAME_FILE: /run/secrets/mongo_root
      #ME_CONFIG_BASICAUTH_PASSWORD_FILE: /run/secrets/mongo_root_password
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_SITE_BASEURL: /mongo/
    secrets:
    - mongo_root
    - mongo_root_password
    networks:
    - aichords
        
secrets:
  mongo_root:
    name: mongo_root
    file: ./auth/mongo_root.txt
  mongo_root_password:
    name: mongo_root_password
    file: ./auth/mongo_root_password.txt
    
networks:
  aichords:
