name: fivechords

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - 'staging'
      - 'main'

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true

jobs:  
  Deploy:
    name: "Deploying services"
    if: startsWith(github.event.pull_request.title, '[r]') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      NGINX: ${{ contains(github.event.pull_request.title, '[nginx]') &&  'nginx' || '' }}
      APP: ${{ contains(github.event.pull_request.title, '[app]') &&  'app' || '' }}
      MONGO: ${{ contains(github.event.pull_request.title, '[mongo]') &&  'mongo' || '' }}
      USER: "root" 
      SSH_KEY: ${{ github.ref == 'refs/heads/staging' && secrets.STAGING_USER_KEY || secrets.PRODUCTION_USER_KEY }}
      SERVER: ${{ github.ref == 'refs/heads/staging' && '70.167.32.130' || '70.167.32.130' }}
      TAGERT_DIR: ${{ github.ref == 'refs/heads/staging' && 'src_stage' || 'src' }}
      PORT: "30854"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: sync&build
        run: |-
          echo "$SSH_KEY" | tr -d '\r' > ssh_key
          chmod 0600 ssh_key
          scp -i ssh_key -P $PORT ./$TARGET_DIR $USER@$SERVER:/workspace
          ssh -o StrictHostKeyChecking=no -i ssh_key -p $PORT $USER@$SERVER "bash /workspace/scripts/deploy_runpod.sh"
          
  DeployChords:
    name: "Updating chords JSON"
    if: startsWith(github.event.pull_request.title, '[chords]') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      SERVER: ${{ github.ref == 'refs/heads/staging' && '70.167.32.130' || '70.167.32.130' }}
      USER: "ci_user" 
      SSH_KEY: ${{ github.ref == 'refs/heads/staging' && secrets.STAGING_USER_KEY || secrets.PRODUCTION_USER_KEY }}
      TAGERT_DIR: ${{ github.ref == 'refs/heads/staging' && 'src_stage' || 'src' }}
      PORT: "30854"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: sync&build
        run: |-
          echo "$SSH_KEY" | tr -d '\r' > ssh_key
          chmod 0600 ssh_key
          scp -i ssh_key -p $PORT ./$TARGET_DIR/config/chords $USER@$SERVER:/workspace/config/chords
          ssh -o StrictHostKeyChecking=no -i ssh_key -p $PORT $USER@$SERVER "bash /workspace/scripts/deploy_runpod.sh"
